### ISSUE TITLE
Not sure making a worker inside a worker is a perfect solution

### ISSUE THREAD

**Issue by Nek-** [Mido22/mp3Recorder#1]
just sayin'

**Comment by Mido22** [comment]
noted, refactoring done, second worker and jquery lib removed... better news, able to compress and send through opus, would push that code to github soon :)

**Comment by Nek-** [comment]
awesome, i'm watching this repo right now ^^ .

(the only thing I can tell is that it would be awesome having native code for thoses... The encoder is quite big)

**Comment by Mido22** [comment]
@Nek- I have pushed the opus codes [here](https://github.com/Mido22/recordOpus), still bit of work to be done... what do you mean by native code?
