### ISSUE TITLE
Worker is not defined

### ISSUE THREAD

**Issue by F1LT3R** [Mido22/mp3Recorder#2]
![screen shot 2014-11-20 at 12 12 03 am](https://cloud.githubusercontent.com/assets/1218446/5120064/e355ec94-7049-11e4-905a-747a270746d5.png)

**Comment by F1LT3R** [comment]
I think this relates to creating a web worker inside another web worker, which you cant do in Chrome, and it seems like you already have an issue open for that; so I will close this.

http://stackoverflow.com/questions/9259251/unable-to-create-web-worker-from-inside-webworker-in-chrome

**Comment by Mido22** [comment]
I have removed the second webworker.

**Comment by F1LT3R** [comment]
:+1:
